# Generated by Django 4.2.29 on 2026-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
