# Generated by Django 4.2.29 on 2026-03-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser_seller',
            name='user',
        ),
    ]
