# Generated by Django 4.2.29 on 2026-03-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_customuser_seller_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser_seller',
        ),
    ]
