# Generated by Django 4.2.29 on 2026-03-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser_buyer',
        ),
    ]
